<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\City;
use App\Models\Area;

class AreaSeeder extends Seeder
{
    public function run()
    {
$postOfficesByDistrict = [
    'New York' => [
        'Manhattan',
        'Brooklyn',
        'Queens',
        'Bronx',
        'Staten Island',
        'Harlem',
        'Chelsea',
        'SoHo',
        'Tribeca',
        'Upper East Side',
        'Upper West Side',
        'Midtown',
        'Greenwich Village',
        'East Village',
        'Financial District',
        'Battery Park City',
        'Hell’s Kitchen',
    ],
    'Los Angeles' => [
        'Hollywood',
        'Downtown',
        'Beverly Hills',
        'Santa Monica',
        'Venice',
        'Chinatown',
        'Koreatown',
        'Silver Lake',
        'Echo Park',
        'Westwood',
        'Brentwood',
        'Pasadena',
        'Bel Air',
        'Malibu',
        'Culver City',
    ],
    'Chicago' => [
        'The Loop',
        'Lincoln Park',
        'Hyde Park',
        'Wicker Park',
        'River North',
        'South Loop',
        'Gold Coast',
        'Chinatown',
        'West Loop',
        'Pilsen',
        'Edgewater',
        'Lakeview',
        'Logan Square',
        'Boystown',
        'Avondale',
    ],
    'Houston' => [
        'Downtown',
        'Midtown',
        'Montrose',
        'The Heights',
        'Museum District',
        'River Oaks',
        'EaDo',
        'West University',
        'Bellaire',
        'Energy Corridor',
        'Greenspoint',
        'Medical Center',
        'Sharpstown',
        'Alief',
        'Spring Branch',
    ],
    'Miami' => [
        'Downtown',
        'Wynwood',
        'Little Havana',
        'Coconut Grove',
        'Brickell',
        'South Beach',
        'Coral Gables',
        'Design District',
        'Edgewater',
        'Midtown',
        'Allapattah',
        'Opa-locka',
        'Doral',
        'Key Biscayne',
        'North Miami',
    ],
    'San Francisco' => [
        'Mission District',
        'SOMA',
        'Chinatown',
        'Castro',
        'Nob Hill',
        'Financial District',
        'Marina District',
        'Tenderloin',
        'Haight-Ashbury',
        'Sunset District',
        'Richmond District',
        'North Beach',
        'Pacific Heights',
        'Bayview',
    ],
    'Dallas' => [
        'Downtown',
        'Deep Ellum',
        'Uptown',
        'Oak Lawn',
        'Bishop Arts District',
        'Design District',
        'Lower Greenville',
        'Addison',
        'Plano',
        'Irving',
        'Richardson',
    ],
    'Atlanta' => [
        'Downtown',
        'Midtown',
        'Buckhead',
        'Virginia Highland',
        'Old Fourth Ward',
        'Inman Park',
        'East Atlanta Village',
        'West End',
        'College Park',
        'Decatur',
    ],
    'Washington, D.C.' => [
        'Georgetown',
        'Capitol Hill',
        'Dupont Circle',
        'Adams Morgan',
        'Foggy Bottom',
        'Columbia Heights',
        'Anacostia',
        'Navy Yard',
        'Shaw',
        'Tenleytown',
    ],
    'Boston' => [
        'Back Bay',
        'Beacon Hill',
        'South End',
        'Fenway',
        'Charlestown',
        'Dorchester',
        'South Boston',
        'Jamaica Plain',
        'Allston',
        'Brighton',
    ],
    'Seattle' => [
        'Downtown',
        'Capitol Hill',
        'Ballard',
        'Fremont',
        'Queen Anne',
        'South Lake Union',
        'Beacon Hill',
        'West Seattle',
        'Rainier Valley',
        'Magnolia',
    ],
    'Denver' => [
        'Downtown',
        'Capitol Hill',
        'Five Points',
        'LoDo',
        'RiNo',
        'Cherry Creek',
        'Highlands',
        'Washington Park',
        'University Hills',
        'Auraria',
    ],
    'Phoenix' => [
        'Downtown',
        'Arcadia',
        'Roosevelt Row',
        'Paradise Valley',
        'Camelback East',
        'Ahwatukee',
        'Alhambra',
        'Maryvale',
        'Encanto',
        'Desert View',
    ],
    'Philadelphia' => [
        'Center City',
        'Old City',
        'University City',
        'Northern Liberties',
        'Fishtown',
        'South Philadelphia',
        'Manayunk',
        'Chestnut Hill',
        'Germantown',
        'Kensington',
    ],
];


        foreach ($postOfficesByDistrict as $districtName => $postOffices) {
            // Find city/district record by name
            $city = City::where('name', $districtName)->first();

            if (!$city) {
                $this->command->info("City/District not found: {$districtName}");
                continue;
            }

            foreach ($postOffices as $index => $postOfficeName) {
                Area::create([
                    'name' => $postOfficeName,
                    'slug' => Str::slug($postOfficeName . '-' . $city->id),
                    'code' => strtoupper(Str::random(5)),
                    'city_id' => $city->id,
                    'description' => "Post office area {$postOfficeName} in district {$districtName}.",
                    'seo_title' => "{$postOfficeName} Area, {$districtName}",
                    'seo_keywords' => "{$postOfficeName}, {$districtName}, post office",
                    'seo_description' => "SEO description for {$postOfficeName} post office in {$districtName}.",
                    'latitude' => null,
                    'longitude' => null,
                    'google_map_location' => null,
                    'priority' => $index + 1,
                ]);
            }
        }
    }
}
